version: '3.8'

services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: admin-dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=${VITE_API_URL}
      - VITE_PUBLIC_IS_HOSTING_API_KEY=${VITE_PUBLIC_IS_HOSTING_API_KEY}
    command: npm run dev 