version: '3.8'

services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: admin-prod
    ports:
      - "${PORT:-8080}:8080"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=${VITE_API_URL}
      - VITE_PUBLIC_IS_HOSTING_API_KEY=${VITE_PUBLIC_IS_HOSTING_API_KEY}
    networks:
      - app-network

networks:
  app-network:
    external: true
    name: infra_app-network