name: Deploy
permissions:
  actions: write       # Necessary to cancel workflow executions
  checks: write        # Necessary to write reports
  pull-requests: write # Necessary to comment on PRs
  contents: read
  packages: write

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts

      - name: Deploy to Production
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          UFW_ALLOWED_PORTS: ${{ secrets.UFW_ALLOWED_PORTS }}
          FAIL2BAN_FINDTIME: ${{ secrets.FAIL2BAN_FINDTIME }}
          FAIL2BAN_BANTIME: ${{ secrets.FAIL2BAN_BANTIME }}
          FAIL2BAN_MAXRETRY: ${{ secrets.FAIL2BAN_MAXRETRY }}
          SSH_MAX_AUTH_TRIES: ${{ secrets.SSH_MAX_AUTH_TRIES }}
          SSH_CLIENT_ALIVE_INTERVAL: ${{ secrets.SSH_CLIENT_ALIVE_INTERVAL }}
          SSH_CLIENT_ALIVE_COUNT_MAX: ${{ secrets.SSH_CLIENT_ALIVE_COUNT_MAX }}
        run: |
          chmod +x ./deployment/scripts/deploy.sh
          ./deployment/scripts/deploy.sh